title: My Site
description: My very nice site

url: 'https://trade-portal.github.io'
baseurl: '/policies'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude: 
  - .gitignore
  - .github
  - docker-compose.yml
  - Dockerfile
  - package-lock.json
  - yarn-error.log
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules

include:
  - _draft
destination: _terms

#########################################
# CUSTOM BELOW

trading_name: Trade Portal
legal_name: Reliable Home Utility Ltd
email_support: support@trade-portal.co.uk