title: My Site
description: My very nice site

url: 'https://policies.trade-portal.co.uk'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude: 
  - .gitignore
  - .github
  - docker-compose.yml
  - Dockerfile
  - package-lock.json
  - yarn-error.log
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules

include:
  - _draft
destination: _terms

#########################################
# CUSTOM BELOW

trading_name: Trade Portal
legal_name: Reliable Home Utility Ltd
legal_address: 16-18 Station Street, Meltham HD9 5QL, United Kingdom
email_support: support@trade-portal.co.uk
company_slug: {{site.trading_name}}
service_url: trade-portal.co.uk
github_repo: trade-portal/policies

example_product_use: create deals
example_integration: Zapier
example_integration_use: to automate your workflow